pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Use Jenkins built-in git plugin
                git branch: 'main', url: 'https://github.com/mcclaude7/alx-backend-python.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh 'python3 -m venv $VENV_DIR'
                sh './$VENV_DIR/bin/pip3 install --upgrade pip'
                sh './$VENV_DIR/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './$VENV_DIR/bin/python3 -m pytest messaging_app/'
            }
        }

        stage('Publish Report') {
            steps {
                junit '**/test-results.xml' // Optional, if using JUnit-compatible pytest plugins
            }
        }
    }
}
