# Generated by Django 5.1.2 on 2025-06-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Conversation_type',
            new_name='conversation_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_body',
        ),
    ]
