#!/bin/bash

echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Applying service..."
kubectl apply -f kubeservice.yaml

echo "Waiting for pods to be ready..."
sleep 10

echo "Getting pod names..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")

echo "Checking logs for green deployment..."
kubectl logs "$GREEN_POD"
